@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTYyODE4MTg2Nn0.YVC8iaRNVltdBiLTHUIFOQdSIKsrHlVK3srFrycIb1A

// Index
GET {{baseUrl}}
###

// List Users
GET {{baseUrl}}/users 
###

POST {{baseUrl}}/users
Authorization: {{token}}
Content-Type: application/json

{
    "name": "LuscasLeo",
    "password": "12312"    
}
###


// Authentication

POST {{baseUrl}}/login
Content-Type: application/json
Connection: keep-alive
Keep-Alive: timeout=5, max=1000

{
  "username": "Luscasleo",
  "password": "12312"
}